#!/bin/bash

## Parameters
# -n Name of file
# -i incremental
# -s source
# -d destination
# 

args=("$@")
i=0
while [[ $i -lt $# ]]
do
	case ${args[$i]} in
		"-s") s="${args[((i + 1))]}";;
		"-f") f="${args[((i +1 ))]}";;
	esac
	i=$((i + 1))
done

## Archivo de configuracion
#  backup.rc

## Logs
#  /var/log/backup.log
log="/var/log/backup.log"

## tar

## Variables
d=`date +%d-%m-%y-%H.%M`

if [[ -z ${f:x} ]]
then
	f="/mnt/USB/Digitaldata$d.tar.gz"
fi

if [[ -z ${s:x} ]]
then
	s="/mnt/Digitaldata"
fi

## Funciones
function writeLog {
echo `date`  `whoami`  $1 >> $log
}

echo $s $f

#tar -zcvf $f $s
