#!/bin/bash

## Parameters
# -n Name of file
# -b {c|i|d} complete | incremetnal | diferencial
# -s source
# -d destination
# 

## Variables
log="/var/log/backup.log"
d=`date +%d-%m-%y-%H.%M`
f="/mnt/USB/Digitaldata$d.tar.gz"
s="/mnt/Digitaldata
	
args=("$@")
i=0
while [[ $i -lt $# ]]
do
	case ${args[$i]} in
		"-s") s="${args[((i + 1))]}";;
		"-f") f="${args[((i +1 ))]}";;
	esac
	i=$((i + 1))
done

## Archivo de configuracion
#  backup.rc

## Funciones
function writeLog {
echo `date`  `whoami`  $1 >> $log
}

echo $s $f

#tar -zcvf $f $s
