#!/bin/bash

## Parameters
# -n Name of file
# -l location of backup
# -s source
#
# 

## Variables
log="/var/log/backup.log"
d=`date +%d-%m-%y_%H.%M`
n="DIF"
l="/mnt/USB/"
s="/mnt/Data/"

## Archivo de configuracion
# backup.rc
function checkConfigurationFile {
if [[ ! -w "$1" ]]; then
	writeLog "No se encuentra el archivo de configuracion ("$l") o hay permiso de lectura" d
	exit -1
fi
}
	checkConfigurationFile $1
function loadConfiguration {
	
	writeLog "Cargado informacion desde $1"
}
	
args=("$@")
i=0

while [[ $i -lt $# ]]
do
	case ${args[$i]} in
		"-c") loadConfiguration "${args[((i+1))]}";;
		"-s") s="${args[((i+1))]}";;
		"-t") t="${args[((i+1))]}";;
		"-l") l="${args[((i+1))]}";;
	esac
	i=$((i+1))
done

function writeLog {
case $2 in
	"d") echo XXX `date`  `whoami`  $1 >> $log ;
		echo XXX Danger $1 ;;
	"w") echo !!! `date`  `whoami`  $1 >> $log ;
		echo !!! Warning $1 ;;
	"" | "*") echo     `date`  `whoami`  $1 >> $log ;;
esac
}

function checkLocation {
if [[ ! -w $l ]]; then
	writeLog "No se encuentra el destino del respaldo ("$l") o no se puede escribir ahi" d
	exit -1
fi
}

function checkSource {
if [[ ! -w $s ]]; then
	writeLog "No se encuentra el origuen de respaldo ("$s") o no se puede escribir ahi" d
	exit -1
fi
}

function doCompleteBackup {
	checkSource
	checkLocation

}

function doIncrementalBackup {
	checkSource
	checkLocation

}

function doDiferencialBackup {
	checkSource
	checkLocation

}


case $t in
	"i")
		doIncrementalBackup ;
		echo Respaldo Incremental $s" > "$l$n"_"$d"_inc.tar.gz";
		writeLog "Respaldo incremetal realizado correctamente";;
	
	"d") 	
		doDiferencialBackup ;
		echo Respaldo diferencial $s" > "$l$n"_"$d"_dif.tar.gz";
		writeLog "Respaldo diferencial realizado correctamente";;
	
	"c" | "f" | *)
		doCompleteBackup ;
		echo Respaldo completo $s" > "$l"$n_"$d"_full.tar.gz";
		writeLog "Respaldo completo realizado correctamente";;
esac


#tar -zcvf $f $s

unset d
unset s
unset n
unset l
unset i
unset log
unset args

exit 0
